[package]
name = "prover-utils"
version = "0.1.0"
edition = "2021"

[dependencies]
serde.workspace = true
ethereum = { path = "../ethereum" }
neutron = { path = "../neutron" }
common.workspace = true
serde_json.workspace = true
[features]
sp1 = ["ethereum/sp1"]
