[workspace]
members = ["common", "domains/ethereum", "prover-utils"]
resolver = "2"


[profile.dev]
opt-level = 3

[workspace.dependencies]
ethereum = { path = "domains/ethereum" }
base64 = "0.22.1"
hex = "0.4"
prover-utils = { path = "prover-utils" }
common = { path = "common" }
tokio = { version = "1.4.11", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
reqwest = "0.12"
url = "2.5"
dotenvy = "0.15"
