[workspace]
members = [
    "common",
    "ethereum",
    "neutron",
    "example-programs/sp1/multi-chain-merkle-program/prover",
    "example-programs/sp1/multi-chain-merkle-program/multi-chain-merkle-guest",
    "verifier",
    "neutron",
]
resolver = "2"

[profile.dev]
opt-level = 3

[workspace.dependencies]
base64 = "0.22.1"
verifier = { path = "verifier" }
multi-chain-merkle-guest = { path = "example-programs/sp1/multi-chain-merkle-program/multi-chain-merkle-guest" }
common = { path = "common" }
sp1-sdk = "4.0.0"
sp1-zkvm = "4.0.0"
tokio = { version = "1.4.11", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
reqwest = "0.12"
url = "2.5"
dotenvy = "0.15"
