[workspace]
members = [
    "common",
    "domains/ethereum",
    "domains/neutron",
    "examples/sp1/cross-chain-merkle-program/prover",
    "examples/sp1/cross-chain-merkle-program/cross-chain-merkle-guest",
    "examples/sp1/cross-chain-message-builder-program/prover",
    "examples/sp1/cross-chain-message-builder-program/cross-chain-message-builder-guest",
    "examples/sp1/vault-zk-rate-program/vault-zk-rate-guest",
    "prover-utils",
    "domains/solana",
    "coprocessor",
]
resolver = "2"

[profile.dev]
opt-level = 3

[workspace.dependencies]
ethereum = { path = "domains/ethereum" }
neutron = { path = "domains/neutron" }
base64 = "0.22.1"
hex = "0.4"
prover-utils = { path = "prover-utils" }
cross-chain-merkle-guest = { path = "examples/sp1/cross-chain-merkle-program/cross-chain-merkle-guest" }
cross-chain-message-builder-guest = { path = "examples/sp1/cross-chain-message-builder-program/cross-chain-message-builder-guest" }
vault-zk-rate-guest = { path = "examples/sp1/vault-zk-rate-program/vault-zk-rate-guest" }
common = { path = "common" }
sp1-sdk = { version = "4.1.2", features = ["native-gnark"] }
sp1-zkvm = "4.1.2"
tokio = { version = "1.4.11", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
reqwest = "0.12"
url = "2.5"
dotenvy = "0.15"
