[workspace]
members = [
    "common",
    "domains/ethereum",
    "domains/neutron",
    "example-programs/sp1/cross-chain-merkle-program/prover",
    "example-programs/sp1/cross-chain-merkle-program/cross-chain-merkle-guest",
    "example-programs/sp1/cross-chain-message-builder-program/prover",
    "example-programs/sp1/cross-chain-message-builder-program/cross-chain-message-builder-guest",
    "prover-utils", "example-programs/sp1/cross-chain-message-builder-program/types",
]
resolver = "2"

[profile.dev]
opt-level = 3

[workspace.dependencies]
base64 = "0.22.1"
prover-utils = { path = "prover-utils" }
cross-chain-merkle-guest = { path = "example-programs/sp1/cross-chain-merkle-program/cross-chain-merkle-guest" }
cross-chain-message-builder-guest = { path = "example-programs/sp1/cross-chain-message-builder-program/cross-chain-message-builder-guest" }
common = { path = "common" }
sp1-sdk = "4.0.0"
sp1-zkvm = "4.0.0"
tokio = { version = "1.4.11", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
reqwest = "0.12"
url = "2.5"
dotenvy = "0.15"
