[workspace]
members = ["common", "ethereum", "prover", "sp1/merkle-program", "ethereum"]
resolver = "2"

[workspace.dependencies]
ethereum = { path = "ethereum" }
merkle-program = { path = "sp1/merkle-program" }
common = { path = "common" }
sp1-sdk = "4.0.0"
sp1-zkvm = "4.0.0"
tokio = { version = "1.4.11", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
reqwest = "0.12"
url = "2.5"
dotenvy = "0.15"
