[package]
name = "vault-zk-rate-types"
version = "0.1.0"
edition = "2021"

[dependencies]
serde.workspace = true
serde_json.workspace = true
ethereum = { path = "../../../../domains/ethereum" }
neutron = { path = "../../../../domains/neutron" }
