[package]
name = "prover"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json.workspace = true
merkle-program.workspace = true
common.workspace = true
sp1-sdk.workspace = true
ethereum = { path = "../ethereum" }

[build-dependencies]
sp1-helper = "4.0.0"
