[package]
version = "0.1.0"
name = "cross-chain-merkle-guest"
edition = "2021"

[dependencies]
sp1-zkvm.workspace = true
common.workspace = true
prover-utils.workspace = true
serde_json.workspace = true
